name: bdaya_oidc_client_android
description: An android implementation for the bdaya_oidc_client plugin.
version: 0.0.1-alpha
homepage: https://github.com/Bdaya-Dev/bdaya_oidc_client


environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bdaya_oidc_client_platform_interface: ^0.0.1-alpha

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.3

flutter:
  plugin:
    implements: bdaya_oidc_client
    platforms:
      web:
        pluginClass: BdayaOidcClientPlugin
        fileName: bdaya_oidc_client_android.dart