name: bdaya_oidc_client_web
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bdaya_oidc_client_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      web:
        pluginClass: BdayaOidcClientWebWeb
        fileName: bdaya_oidc_client_web_web.dart